=== Clakatakito/Practicas/Servicios/db/XML-DTD/Practica 5/fichero.dtd
<!ELEMENT albara (numero, data, client, articles)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT client (nom, poblacio)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT poblacio (#PCDATA)>
<!ELEMENT articles (compra+)>
<!ELEMENT compra (article, quantitat, descompte?)>
<!ELEMENT granel EMPTY>
<!ELEMENT descompte (#PCDATA)>
<!ELEMENT quantitat (#PCDATA)>
<!ELEMENT article (descripcio, granel?, ampolla?, preu)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT ampolla EMPTY>
<!ELEMENT preu (#PCDATA)>

<!ATTLIST client id ID #REQUIRED>
<!ATTLIST article codi ID #REQUIRED>

=== Clakatakito/Practicas/programacion/Lenguajes Estructurales/XML-DTD/Practica 5/albara5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE albara SYSTEM "fichero.dtd">
<albara>
    <numero>5</numero>
    <data>2011-10-02</data>
    <client id="m1">
        <nom>Pere Garcia</nom>
        <poblacio>Figueres</poblacio>        
    </client>
    <articles>
        <compra>
            <article codi="m12">
                <descripcio>Vi negre Rioja reserva. Marques de Riscal 75 cl</descripcio>
                <ampolla/>
                <preu>12.85</preu>
            </article>
            <quantitat>2</quantitat>
        </compra>
        <compra>
            <article codi="m10">
                <descripcio>Vi Blanc D.O.Pened√®s. Vinya Sol Torres 75 cl</descripcio>
                <ampolla/>
                <preu>4.80</preu>
            </article>
            <quantitat>1</quantitat>
        </compra>        
    </articles>    
</albara>

sexo
