<?xml version="1.0" encoding="UTF-8"?> <!-- Tiene que estar en la primera linea, sino no funciona -->

<!DOCTYPE personas [ <!-- Definimos el elemento personas -->

    <!ELEMENT personas (persona+)> <!-- Dentro del elemento "personas" esta el elemento "persona", el "+" es porque hay mas de un elemento persona -->
    <!ELEMENT persona (nombre,edad)> <!-- Dentro del elemento "persona" estan los elementos "nombre" y "edad" (el orden importa) -->
    <!ATTLIST persona estudiante CDATA #REQUIRED> <!-- Dentro del elemento "persona" esta el atributo "estudiante", el "CDATA" nos indica que sera texto normal, y el "#REQUIED" ya hos lo imaginais -->
    <!ELEMENT nombre (#PCDATA)> <!-- Dentro del elemento "nombre" también habrá texto -->
    <!ELEMENT edad (#PCDATA)> <!-- Dentro del elemento "edad" también habrá texto, recordar con xml no usa numeros, usa textos(strings) -->

]>

<personas>
    <persona estudiante = "Si">
        <nombre>Alex</nombre>
        <edad>19</edad>
    </persona>
    <persona estudiante = "No">
        <nombre>Pepe</nombre>
        <edad>15</edad>
    </persona>
</personas>