=== Clakatakito/Practicas/programacion/Lenguajes Estructurales/XML-DTD/examen/gestioProjectes.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT projectes (projecte+, tasques?)>
<!ELEMENT projecte (nom, descripcio, data_llancament, equip, tasques)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT data_llancament (#PCDATA)>
<!ELEMENT equip (membre+)>
<!ELEMENT membre (nom)>
<!ELEMENT tasques (tasca+)>
<!ELEMENT tasca (data_inici, data_fi, prioritat)>
<!ELEMENT data_inici (#PCDATA)>
<!ELEMENT data_fi (#PCDATA)>
<!ELEMENT prioritat (#PCDATA)>



<!ATTLIST projecte id_proj ID #REQUIRED>
<!ATTLIST membre funciÃ³ CDATA #REQUIRED>
<!ATTLIST tasca id_unic ID #REQUIRED>
<!ATTLIST tasca estat (Finalitzada | Progres | Pendent) #REQUIRED>

=== Clakatakito/Practicas/programacion/Lenguajes Estructurales/XML-DTD/examen/gestioProjectes.xml
<!DOCTYPE projectes SYSTEM "gestioProjectes.dtd">
<projectes>
    <projecte id_proj="P001">
        <nom>App Mòbil de Viatges</nom>
        <descripcio>Desenvolupament d'una aplicació per a la reserva de vols i hotels.</descripcio>
        <data_llancament>2025-01-30</data_llancament>
        <equip>
            <membre funció="Desenvolupador">
                <nom>Albert Soler</nom>
            </membre>
            <membre funció="Analista">
                <nom>Marta Roca</nom>
            </membre>
        </equip>
        <tasques>
            <tasca id_unic="T101" estat="Finalitzada">
                <data_inici>2024-11-01</data_inici>
                <data_fi>2024-11-15</data_fi>
                <prioritat>Alta</prioritat>
            </tasca>
            <tasca id_unic="T102" estat="Progres">
                <data_inici>2024-11-16</data_inici>
                <data_fi>2024-12-30</data_fi>
                <prioritat>Mitjana</prioritat>
            </tasca>
        </tasques>
    </projecte>

    <projecte id_proj="P002">
        <nom>Plataforma E-commerce</nom>
        <descripcio>Migració de la botiga online a un nou CMS.</descripcio>
        <data_llancament>2025-04-01</data_llancament>
        <equip>
            <membre funció="Tester">
                <nom>Núria Bosch</nom>
            </membre>
        </equip>
        <tasques>
            <tasca id_unic="T201" estat="Pendent">
                <data_inici>2025-01-05</data_inici>
                <data_fi>2025-02-15</data_fi>
                <prioritat>Baixa</prioritat>
            </tasca>
        </tasques>
    </projecte>
</projectes>
